public import Voxels

/// A detailed diagnostic event from processing a single voxel.
public struct CADetailedDiagnostic<T: Sendable>: Sendable {
    /// The index of the voxel.
    public let index: VoxelIndex
    /// The name of the rule.
    public let rule: String
    /// The voxel's value prior to invoking the rule.
    public let initialValue: T?
    /// The voxel's value after to invoking the rule.
    /// A `nil` value indicates the voxel was not changed from the initial value.
    public let finalValue: T?
    /// The collection of diagnostic messages, if any, generated by the rule.
    public let messages: [String]
}
