public import Voxels

/// A diagnostic event from processing a single voxel.
public struct CADiagnostic: Sendable {
    /// The index of the voxel.
    public let index: VoxelIndex
    /// The name of the rule.
    public let rule: String
    /// The collection of diagnostic messages, if any, generated by the rule.
    public let messages: [String]
}
